---
title: "Artificial Intelligence & Machine Learning"
---

Your Neighborhood Scientist (YNS) recognises the potential benefits of Machine
Learning (ML) and Artificial Intelligence (AI) in improving operational
efficiency and analytical capabilities. This policy outlines the responsible and
ethical use of AI/ML when preparing content for YNS while ensuring
that these technologies are used exclusively for repetitive, non-creative, and
analytical tasks.

##  Scope

This policy applies to all authors, editors, reviewers, and any other individuals or entities collaborating with YNS.

## Purpose of AI/ML

The primary purpose of implementing AI/ML within YNS is to enhance productivity,
streamline operations, and assist in analytical tasks that require data-driven
decision-making. The tools considered are analytical, text-based,
speech/audio-based, as well as visual.

**Creative work is to remain the sole responsibility of humans.**

**The quality of YNS and the personal style of our writers must be protected.**

## Authorization and Communication

### Authorization

The use of AI/ML for any purpose within YNS must be authorized by the handling
editor. Editors must ensure that the application aligns with the objectives of
this policy.

### Communication

Any use of AI/ML, regardless of its nature, must be communicated during the
submission process.

## Prohibited Uses

AI/ML should not be employed for writing or creative work. The generation of
original written and artistic content must remain the domain of humans.

## Permitted Uses

AI/ML can be used for the following purposes, provided they do not violate any
legal or ethical guidelines:

1. Repetitive Tasks. Automation of routine and repetitive tasks to increase efficiency and reduce manual labour.
2. Minor Tasks. Tasks such as shortening text, grammar checks, or image filters.

## Data Privacy and Security

All AI/ML activities must comply with data privacy laws and ensure the security
of any data used or generated by AI/ML systems.

## Accountability

Each person associated with YNS is accountable for responsibly and ethically
using AI/ML. When unsure, persons are to seek advice from one of the editors or
to contact <info@neighborhoodscientist.org>.

## Review and Revision

This policy shall be subject to periodic review and revision as technology
evolves or as needs change. Any changes to this policy will be
communicated to all relevant stakeholders.

This Machine Learning and Artificial Intelligence Policy is intended to provide
guidelines for the ethical and responsible use of AI/ML. It ensures that ML and
AI are harnessed to improve efficiency and analytical capabilities while
maintaining the creativity and integrity of written and artistic work produced
by the organization. This policy was not written using AI/ML.

## Contact Information

If you have any questions or concerns related to this policy,
please contact <info@neighborhoodscientist.org>.

> This policy was adapted from the _Consilience_ journal's [AI/ML policy](https://docs.google.com/document/d/1_kLeZA5d1FjnRQ3-O5BMkdZ95yT7mnJq/edit?tab=t.0).
