---
title: "Author-Publisher Agreement"
---

By submitting your work to Your Neighborhood Scientist (YNS) you (The Author)
agree to the following terms, if your work is published:

- In submitting to YNS, The Author confirms that they have full authorial rights to submit the enclosed work, and that there are no prior or conflicting copyright issues with the submission.
- The Author grants YNS the non-exclusive rights for printing, publishing, and distributing their work.
- The Author agrees that YNS will publish their work under a CC BY-SA license.
- The Author agrees that the work has not been published anywhere else, prior to publication in YNS.
- The Author may submit their work to other publishers, but if the work is published elsewhere (in print, electronic form, online, or recorded) The Author will ensure that proper citations to YNS (as first publisher) will accompany any other publication.
- Following consultation with our Editors, The Author will provide YNS with an accurate, edited final version of their work and will accept responsibility for any errors represented within that final version.
- YNS will publish the work without compensation to The Author.

Please get in touch with us via <mailto:info@neighborhoodscientist.org> if you have any questions about any of the above.

– The YNS Team
