---
title: "Code of Conduct"
---

As contributors of Your Neighborhood Scientist (YNS), we pledge to respect all people
who contribute through writing, editing, and other activities that support the YNS mission.

We are committed to making participation in this project a harassment-free
experience for everyone, regardless of level of experience, gender, gender
identity and expression, sexual orientation, disability, personal appearance,
body size, race, ethnicity, age, or religion.

Examples of unacceptable behavior by participants include the use of sexual
language or imagery, derogatory comments or personal attacks, trolling, public
or private harassment, insults, or other unprofessional conduct.

YNS leadership has the right and responsibility to reject article submissions
and other contributions that are not aligned to this Code of Conduct.
Contributors who do not follow the Code of Conduct may be removed from the team.

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting one or more of the YNS board members or sending an email
to <info@neighborhoodscientist.org>.

This Code of Conduct is adapted from the Contributor Covenant, version 1.0.0,
available at
https://www.contributor-covenant.org/version/1/0/0/code-of-conduct.html
