### Specific guidelines

Articles should be less than 1,000 words and must contain language that is
accessible to the general public. You can use [this online
tool](https://hemingwayapp.com/readability-checker) to gauge what level your
writing is at and adjust sentences that might be inaccessible to a
non-scientific audience.

We realize many of these are complex topics that we could write books about. We
ask that you distill your message down to a specific topic, as this will be most
accessible to the general public. If you feel that your topic necessitates a
longer article, we would be happy to consider releasing a multi-part series.

Please include a short (1-3 sentence) author bio for the end of your article.
You can include your current job, education, a little about your hobbies, a link
to your personal website, or anything you like. Feel free to let your
personality shine through! Examples:

- [name] is a [title] at [company]. When she's not too busy fixing bugs in her code, she enjoys running, climbing, and trying to keep her 19 plants alive.
- [name] received their MS in [field] from [university] and is currently looking for their next gig. [name] has a passion for open science, baking, and table top board games.
- [name] is well known among his friends and colleagues as the go-to data wrangler and phone repair guru. At this point he should probably start his own business for electronics repair, but in the meantime he is enjoying [actual position] for [employer].

In addition, we would love to include a picture of you with the article to give
readers a sense of the diversity of humans who do science. We would especially
love to see a photo of you in action doing science, a hobby you enjoy, or even
just a candid shot from your everyday life. If this is okay, please include a
picture (horizontal if possible) that will serve as the header for your article.
Also, let us know your handle/username for any social media sites you use so we
can tag you when we publish your article!

- BlueSky
- Facebook
- Instagram
- Personal website, academic profile, or other link we should include in your author bio
- GitHub -- if you have a GitHub account, we'll tag you as the commit author in our website repository

When you're ready, please send a draft of your article to
<mailto:audrey@neighborhoodscientist.org>. We'll edit your article and prepare
it for publication, and then send it back to you for your final approval before
it gets sent out. Articles will be distributed every 1-2 weeks via our email
newsletter, blog, and other social media.
