---
title: Guidelines for writing a "Science in our communities" article
---
Hi! We are so glad you are considering writing a "Science in our communities" article for Your Neighborhood Scientist. These articles are written by scientists and community members about a particular scientific or medical achievement and the impact it has on the community, which may not be obvious to the average person.

The goal of these articles is to communicate exciting scientific and medical advances in a way that is accessible to the general public. We also want to combat misinformation about some specific scientific and medical advances -- for example, vaccines. Here are some sample topics:

- CAR-T cell therapy: re-engineering our own immune system to fight cancer
- Cochlear implants: electrically stimulating our auditory nerves to help deaf individuals hear
- mRNA vaccines: developing fast vaccines for viruses that can cause pandemics, including COVID-19 and H5N1
- Technologies that mitigate impacts of climate change
- Advances from basic science and exploratory research with unexpected applications (e.g. CRISPR, space exploration)

After reading, we want people to feel excited about the amazing scientific and
medical advances that their taxpayer money funds. We want your audience to feel
smart (don't we all?), because they are able to understand the science you are
presenting and its impacts. We want them to be empowered to talk to their
neighbor about exciting topics like engineered immune systems that tackle
cancer. To achieve this, we encourage you to present concepts simply and
concisely, highlighting the key takeaways and avoiding getting lost in the
technical weeds. We also really like the advice from
[this article](https://www.forbes.com/sites/marshallshepherd/2016/11/22/9-tips-for-communicating-science-to-people-who-are-not-scientists/)
about presenting science to non-scientists.

We appreciate that especially with science concepts, a picture can tell a
thousand words. We also love a good cartoon or analogy that helps your audience
remember your take-away message. If you feel like a doodle/diagram/illustration
would really help you get your point across, we can work with you to include
this in your article.

{{< include _guidelines.qmd >}}
